name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.3.21202.5'

    - name: Dotnet restore
      run: dotnet restore MihuBot

    - name: Dotnet build (Release)
      run: dotnet build MihuBot -c Release --no-restore