name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.3.21202.5'

    - name: Dotnet build
      run: dotnet build MihuBot -c Release

    - name: Push to release branch
      run: |
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email 25307628+MihaZupan@users.noreply.github.com
        git push origin master:release -f
