name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.3.21202.5'

    - name: Dotnet restore
      run: dotnet restore MihuBot

    - name: Dotnet build
      run: dotnet build MihuBot

    #- name: Dotnet test
    #  run: dotnet test MihuBot

    - name: Dotnet publish
      run: dotnet publish MihuBot -c Release -r linux-x64 --self-contained false -p:PublishSingleFile=true -o artifacts

    - name: Zip artifacts
      run: zip -r "${GITHUB_SHA}.zip" artifacts

    - name: Copy to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: ${GITHUB_SHA}.zip"
        target: ${{ secrets.PROD_UPDATE_PATH }}